[package]
name = "rust-pad"
version = "0.1.0"
edition = "2021"
description = "test app"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }

[package.metadata.bundle]
name = "Rustpad"
identifier = "io.div.rustpad"
